import { NextRequest, NextResponse } from 'next/server'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/lib/auth'
import { prisma } from '@/lib/prisma'

export async function GET() {
  const session = await getServerSession(authOptions)
  if (!session) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  const cities = await prisma.city.findMany({
    orderBy: { createdAt: 'desc' },
  })

  return NextResponse.json(cities)
}

export async function POST(request: NextRequest) {
  const session = await getServerSession(authOptions)
  if (!session) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  try {
    const data = await request.json()
    
    const city = await prisma.city.create({
      data: {
        name: data.name,
        slug: data.slug,
        state: data.state,
        zipCode: data.zipCode,
        metaTitle: data.metaTitle,
        metaDescription: data.metaDescription,
        keywords: data.keywords,
        description: data.description,
        localContent: data.localContent,
        neighborhoods: data.neighborhoods,
        latitude: data.latitude,
        longitude: data.longitude,
        published: data.published ?? true,
      },
    })

    // Auto-generate location pages
    await generateLocationPages(city.id, city.slug)

    return NextResponse.json(city)
  } catch (error: any) {
    console.error('Error creating city:', error)
    return NextResponse.json(
      { error: error.message || 'Failed to create city' },
      { status: 500 }
    )
  }
}

async function generateLocationPages(cityId: string, citySlug: string) {
  // Generate general location page
  await prisma.locationPage.upsert({
    where: { slug: `flooring-installer-${citySlug}` },
    update: {},
    create: {
      type: 'GENERAL',
      slug: `flooring-installer-${citySlug}`,
      cityId,
      autoGenerated: true,
    },
  })

  // Generate service-specific location pages for each published service
  const services = await prisma.service.findMany({
    where: { published: true },
  })

  for (const service of services) {
    await prisma.locationPage.upsert({
      where: { slug: `${service.slug}-${citySlug}` },
      update: {},
      create: {
        type: 'SERVICE_CITY',
        slug: `${service.slug}-${citySlug}`,
        cityId,
        serviceId: service.id,
        autoGenerated: true,
      },
    })
  }
}
